#!/usr/bin/env bash
# Provision the local Postgres role and databases for development and tests.
#
# Idempotent: safe to run repeatedly. Uses peer auth over the unix socket (the current OS user must
# be a Postgres superuser), then creates a `homecare` LOGIN role and the `homecare` and
# `homecare_test` databases owned by it. The role connects over TCP with SCRAM where a password is
# required, so a generated dev password is set and written to .env.
#
# .env is gitignored. Production note (docs/16-open-questions.md B): the password below is a
# development convenience. Real environments get credentials from a secrets store, never from a file
# named .env.

set -euo pipefail
cd "$(dirname "$0")/.."

DB_USER="homecare"

# Reuse an existing dev password from .env so re-running does not invalidate a running app.
DB_PASSWORD="$(grep -m1 -E '^HOME_CARE_DB_PASSWORD=' .env 2>/dev/null | cut -d= -f2- || true)"
if [ -z "$DB_PASSWORD" ]; then
  DB_PASSWORD="$(openssl rand -hex 16)"
fi

ADMIN="${PGDEV_ADMIN:-}"
if [ -z "$ADMIN" ]; then
  ADMIN="$(whoami)"
fi

# Password is generated hex (alnum only), so it is safe to inline into SQL.
if psql -U "$ADMIN" -d postgres -tAc "select 1 from pg_roles where rolname='${DB_USER}'" | grep -q 1; then
  psql -U "$ADMIN" -d postgres -c "alter role ${DB_USER} with login password '${DB_PASSWORD}'" >/dev/null
else
  psql -U "$ADMIN" -d postgres -c "create role ${DB_USER} login password '${DB_PASSWORD}'" >/dev/null
fi

for db in homecare homecare_test; do
  if ! psql -U "$ADMIN" -d postgres -tAc "select 1 from pg_database where datname='${db}'" | grep -q 1; then
    psql -U "$ADMIN" -d postgres -c "create database ${db} owner ${DB_USER}"
  fi
done

if [ ! -f .env ]; then
  cat > .env <<EOF
# Generated by scripts/provision-db.sh — local development only.
HOME_CARE_DB_PASSWORD=${DB_PASSWORD}
DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@127.0.0.1:5432/homecare
DATABASE_URL_TEST=postgres://${DB_USER}:${DB_PASSWORD}@127.0.0.1:5432/homecare_test
REDIS_URL=redis://127.0.0.1:6379
JWT_ACCESS_TTL_SECONDS=900
JWT_REFRESH_TTL_SECONDS=2592000
PORT=3000
EOF
  echo "wrote .env"
else
  # Refresh the password in an existing .env so the app and this script stay in agreement.
  sed -i.bak -E \
    -e "s#^HOME_CARE_DB_PASSWORD=.*#HOME_CARE_DB_PASSWORD=${DB_PASSWORD}#" \
    -e "s#^DATABASE_URL=.*#DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@127.0.0.1:5432/homecare#" \
    -e "s#^DATABASE_URL_TEST=.*#DATABASE_URL_TEST=postgres://${DB_USER}:${DB_PASSWORD}@127.0.0.1:5432/homecare_test#" \
    .env
  rm -f .env.bak
  echo "refreshed .env"
fi

echo "role and databases ready: ${DB_USER}@127.0.0.1:5432 {homecare, homecare_test}"